name: Lint

on: push

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --print-width 120 --tab-width 4 --end-of-line auto --check src/public/**/*.js src/public/**/*.css src/public/**/*.html
