name: Lint

on: push

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  # This part is also where you can pass other options, for example:
                  dry: True
                  prettier_options: --check src/public/**/*.js src/public/**/*.html
